CREATE TABLE ORDERCOFFEE(
	ORDERNUM NUMBER(4) PRIMARY KEY,
	MEMBERID VARCHAR2(30) NOT NULL,
	ORDERDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_ORDER
START WITH 100
INCREMENT BY 1;

ALTER TABLE ORDERCOFFEE
ADD CONSTRAINT FK_CFORDER_ID FOREIGN KEY(MEMBERID)
	REFERENCES MEMBER(ID);
	
INSERT INTO ORDERCOFFEE VALUES (SEQ_ORDER.NEXTVAL, 'aaa', SYSDATE);

select * from ORDERCOFFEE

SELECT ORDERNUM 
	FROM(
		SELECT ROWNUM AS RNUM, ORDERNUM 
			FROM (
				SELECT * FROM ORDERCOFFEE
				ORDER BY ORDERDATE DESC)
		) 
WHERE RNUM = 1

Select *  from
ORDER_LIST l, ORDERCOFFEE c
WHERE l.ordernum = c.ordernum
	and c.ORDERNUM IN (select ORDERNUM from ORDERCOFFEE 
					WHERE MEMBERID = 'aaa')
ORDER BY c.ORDERNUM DESC
